// Generated by https://quicktype.io

import { Room } from './room.interface';

export interface Property {
  id: number;
  name: string;
  details: string;
  address: string;
  postalCode: string;
  city: string;
  country: string;
  latitude: string;
  longitude: string;
  bedrooms: number;
  bathrooms: number;
  is_available: boolean;
  property_size: number;
  smoking_allowed: boolean;
  pets_allowed: boolean;
  couples_allowed: boolean;
  occupantCount: number;
  deletedAt: null;
  userEmail: string;
  rooms: Room[];
}
