// Generated by https://quicktype.io

import { Amenity } from './amenity.interface';
import { Property } from './property.interface';

export interface Room {
  id: number;
  name: string;
  details: string;
  precio: string;
  is_available: boolean;
  room_size: number;
  bed_type: string;
  available_from: string;
  utilities_included: boolean;
  deposit_required: boolean;
  services_included: string;
  photos: string;
  deletedAt: null;
  propertyId: number;
  userEmail: string;
  amenityIds?: number[];
  property?: Property;
  amenities?: Amenity[];
}
