// Generated by https://quicktype.io

export interface User {
  id: number;
  username: string;
  email: string;
  role: string;
  first_name: string;
  last_name: string;
  phone: number;
  address: string;
  date_of_birth: null;
  photo: string;
  registration_date: string;
  last_update: string;
  deletedAt: null;
}
